// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DAL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Customer_CustomerDeposit_OneToMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customer_CustomerDeposit_OneToMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201510102105323_Customer_CustomerDeposit_OneToMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
